-- MySQL Script generated by MySQL Workbench
-- Mon Jan 25 15:32:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gbaf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gbaf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gbaf` DEFAULT CHARACTER SET utf8 ;
USE `gbaf` ;

-- -----------------------------------------------------
-- Table `gbaf`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gbaf`.`accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `question` VARCHAR(255) NOT NULL,
  `answer` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gbaf`.`actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gbaf`.`actors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `filename` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `filename_UNIQUE` (`filename` ASC),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gbaf`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gbaf`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `accounts_id` INT NOT NULL,
  `actors_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_accounts_idx` (`accounts_id` ASC),
  INDEX `fk_comments_actors1_idx` (`actors_id` ASC),
  CONSTRAINT `fk_comments_accounts`
    FOREIGN KEY (`accounts_id`)
    REFERENCES `gbaf`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_actors1`
    FOREIGN KEY (`actors_id`)
    REFERENCES `gbaf`.`actors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gbaf`.`votes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gbaf`.`votes` (
  `accounts_id` INT NOT NULL,
  `actors_id` INT NOT NULL,
  `opinion` TINYINT NOT NULL,
  PRIMARY KEY (`accounts_id`, `actors_id`),
  INDEX `fk_accounts_has_actors_actors1_idx` (`actors_id` ASC),
  INDEX `fk_accounts_has_actors_accounts1_idx` (`accounts_id` ASC),
  CONSTRAINT `fk_votes_accounts1`
    FOREIGN KEY (`accounts_id`)
    REFERENCES `gbaf`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_votes_actors1`
    FOREIGN KEY (`actors_id`)
    REFERENCES `gbaf`.`actors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
